language: cpp
os: linux
dist: bionic

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get install liblua5.3-dev lua5.3
    - sudo updatedb
    - sudo locate lua.h

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
